version: '3.8'

services:
  mysql:
    image: mysql:8.0.41-debian
    container_name: mysql-8.0.41
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mail_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mailnet

  backend:
    build:
      context: ./BE
    container_name: spring-backend
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mail_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - mailnet
    volumes:
      - ./logs/backend:/app/logs

  frontend:
    build:
      context: ./FE
    container_name: react-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - mailnet

  mailserver:
    build:
      context: ./mailserver
    container_name: mailserver
    depends_on:
      - mysql
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
    volumes:
      - ./logs/mailserver:/var/log/mailserver
    networks:
      - mailnet

volumes:
  mysql_data:

networks:
  mailnet:
    external: false
