version: '3.8'

services:
  backend:
    build:
      context: ./BE
    container_name: spring-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-8.0.41:3306/mail_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - mailnet

  frontend:
    build:
      context: ./FE
    container_name: react-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - mailnet

networks:
  mailnet:
    external: false
